# PROVA INTELIGÊNCIA ARTIFICIAL
Aluno: Kelvin Brenand - 20180005270

# Questão 3:

# Imports

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
dataset = pd.read_csv("https://drive.google.com/uc?export=download&id=1qdGJrpXYsRNrYZX5IcE6gXp6wltZJaft")

# Pré-processamento

In [ ]:
#Remove linhas com NaN, remove linhas com número de quartos igual a 0, 7, 8, 9 e 10
dataset.dropna(subset = ["Location"], inplace=True)
dataset = dataset.rename(columns={'No. of Bedrooms': 'Bedrooms'})
dataset = dataset[dataset.Bedrooms != 0]
dataset = dataset[dataset.Bedrooms != 7]
dataset = dataset[dataset.Bedrooms != 8]
dataset = dataset[dataset.Bedrooms != 9]
dataset = dataset[dataset.Bedrooms != 10]

In [ ]:
#Correlações
print(np.corrcoef(dataset["No. of Bathrooms"], dataset["Bedrooms"]))
print(np.corrcoef(dataset["No. of Receptions"], dataset["Bedrooms"]))

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
#Remove colunas, realiza oversampling e downsampling
X = dataset.iloc[:, [2, 4, 8]].values #Price, Area, Location
y = dataset.iloc[:, 5].values
oversample = RandomOverSampler(sampling_strategy={6:200})
X, y = oversample.fit_resample(X, y)
undersample = RandomUnderSampler(sampling_strategy='all')
X, y = undersample.fit_resample(X, y)

In [ ]:
#Tranforma 'Location' de string para int (0-362)
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
#Divide os dados entre conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
#Normalização
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Treinamento

In [ ]:
#Treino com distância euclidiana
classifier = KNeighborsClassifier(n_neighbors = 51, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=51)

In [ ]:
#Treino com distância de manhattan
classifier = KNeighborsClassifier(n_neighbors = 35, metric = 'manhattan')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=35)

In [ ]:
#Treino com distância de chebyshev
classifier = KNeighborsClassifier(n_neighbors = 35, metric = 'chebyshev')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='chebyshev', n_neighbors=151)

In [ ]:
y_pred = classifier.predict(X_test)

# Testes

In [ ]:
#Matriz de confusão
print(metrics.confusion_matrix(y_test, y_pred))

[[32  2  0  0  0  0]
 [11 13  8  2  0  0]
 [ 0 13 21  6  2  0]
 [ 0  1  6 23  4  8]
 [ 0  0  4  8 21  8]
 [ 0  0  1  4 12 30]]


In [ ]:
#Métricas
print(metrics.classification_report(y_test, y_pred, target_names=['1','2','3','4','5','6']))

              precision    recall  f1-score   support

           1       0.74      0.94      0.83        34
           2       0.45      0.38      0.41        34
           3       0.53      0.50      0.51        42
           4       0.53      0.55      0.54        42
           5       0.54      0.51      0.53        41
           6       0.65      0.64      0.65        47

    accuracy                           0.58       240
   macro avg       0.57      0.59      0.58       240
weighted avg       0.57      0.58      0.58       240



In [ ]:
print(classifier.predict([X_test[17]]))

[1]
