# 1.1  Introduction
## 1.1.1  About This Experiment
- This experiment helps trainees understand the basic syntax of TensorFlow 2.x by introducing a series of tensor operations of TensorFlow 2.x, including tensor creation, slicing, and indexing, tensor dimension modification, tensor arithmetic operations, and tensor sorting.

## 1.1.2  Objectives
- Upon completion of this task, you will be able to:
  - Understand how to create a tensor.
  - Master the tensor slicing and indexing methods.
  - Master the syntax for tensor dimension modification.
  - Master arithmetic operations of tensors.
  - Master the tensor sorting method.
  - Dive deeper into eager execution and AutoGraph based on code.

# 1.2 Experiment Steps 
## 1.2.1 Introduction to Tensors 
- In TensorFlow, tensors are classified into constant tensors and variable tensors. 
  - A defined constant tensor has an unchangeable value and dimension, and a defined variable tensor has a changeable value and an unchangeable dimension. 
  - In neural networks, variable tensors are generally used as matrices for storing weights and other information, and are a type of trainable data. Constant tensors can be used as variables for storing hyperparameters or other structured data. 

### 1.2.1.1  Tensor Creation
#### 1.2.1.1.1  Creating a Constant Tensor
- Common methods for creating a constant tensor include:
  - tf.constant(): creates a constant tensor.
  - tf.zeros(), tf.zeros_like(), tf.ones(), and tf.ones_like(): create an all-zero or all-one constant tensor.
  - tf.fill(): creates a tensor with a user-defined value.
  - tf.random: creates a tensor with a known distribution.
- Creating a list object by using NumPy, and then converting the list object into a tensor by using tf.convert_to_tensor.

Step 1: tf.constant() 
- tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False):
  - value: value
  - dtype: data type
  - shape: tensor shape
  - name: constant name
  - verify_shape: Boolean value, used to verify the shape of a value. The default value is False. If verify_shape is set to True, the system checks whether the shape of a value is consistent with the value of shape. If they are inconsistent, the system reports an error.

In [4]:
import tensorflow as tf

In [8]:
const_a = tf.constant(
    [1, 2, 3, 4,5,6], shape=[3, 2], dtype=tf.float32
)  # Create a 2x2 matrix with values 1, 2, 3, and 4.
const_a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [9]:
print("value of the constant const_a:", const_a.numpy())
print("data type of the constant const_a:", const_a.dtype)
print("shape of the constant const_a:", const_a.shape)
print("name of the device that is to generate the constant const_a:", const_a.device)

value of the constant const_a: [[1. 2.]
 [3. 4.]
 [5. 6.]]
data type of the constant const_a: <dtype: 'float32'>
shape of the constant const_a: (3, 2)
name of the device that is to generate the constant const_a: /job:localhost/replica:0/task:0/device:CPU:0


Step 2: tf.zeros(), tf.zeros_like(), tf.ones(), and tf.ones_like()
- Usages of tf.ones() and tf.ones_like() are similar to those of tf.zeros() and tf.zeros_like(). Therefore, the following describes only the usages of tf.ones() and tf.ones_like().
- Create a constant with the value 0.
  - tf.zeros(shape, dtype=tf.float32, name=None):
    - shape: tensor shape
    - dtype: data type
    - name: constant name

In [10]:
zeros_b = tf.zeros(
    shape=[3, 3], dtype=tf.int32
)  # Create a 2x3 matrix with all values being 0.
zeros_b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

- Create a tensor whose value is 0 based on the input tensor, with its shape being the same as that of the input tensor. 
  - tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True):
    - input_tensor: tensor
    - dtype: data type
    - name: tensor name
    - optimize: indicates whether optimization is enabled.

In [11]:
zeros_like_c = tf.zeros_like(const_a)
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

Step 3: tf.fill()
- Create a tensor and fill it with a specific value. 
  - tf.fill(dims, value, name=None):
    - dims: tensor shape, same as shape above.
    - value: tensor value
    - name: tensor name

In [12]:
fill_d = tf.fill([2, 4], 10)  # Create a 2x3 matrix with all values being 8.
fill_d.numpy()

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

Step 4: tf.random
- This module is used to generate a tensor with a specific distribution. Common methods in this module include tf.random.uniform(), tf.random.normal(), and tf.random.shuffle(). The following describes how to use tf.random.normal().
- Create a tensor that conforms to a normal distribution. 
  - tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32,seed=None, name=None):
    - shape: data shape
    - mean: mean value with a Gaussian distribution
    - stddev: standard deviation with a Gaussian distribution
    - dtype: data type
    - seed: random seed
    - name: tensor name

In [15]:
random_e = tf.random.normal([6, 3], mean=5, stddev=1.0, seed=1)
random_e.numpy()

array([[4.1886816, 6.4845986, 5.0653296],
       [2.5572958, 5.0992484, 5.591224 ],
       [5.592823 , 2.8770704, 4.277103 ],
       [4.9437294, 5.6435447, 4.735676 ],
       [6.856633 , 5.5678415, 4.617164 ],
       [3.5146565, 6.261771 , 4.974694 ]], dtype=float32)

Step 5 Create a list object by using NumPy, and then convert the list object into a tensor by using tf.convert_to_tensor.
- This method can convert a given value into a tensor. tf.convert_to_tensor can be used to convert a Python data type into a tensor data type available to TensorFlow.
  - tf.convert_to_tensor(value,dtype=None,dtype_hint=None,name=None):
    - value: value to be converted
    - dtype: data type of the tensor
    - dtype_hint: optional element type for the returned tensor, used when dtype is set to None. In some cases, a caller may not consider dtype when calling tf.convert_to_tensor. Therefore, dtype_hint can be used as a preference.

In [18]:
# Create a list.
list_f = [1, 2, 3, 4, 5, 6,9]
# View the data type.
type(list_f)

list


##### 1.2.1.1.2  Creating a Variable Tensor
In TensorFlow, variables are operated using the tf.Variable class. tf.Variable indicates a tensor. The value of tf.Variable can be changed by running an arithmetic operation on tf.Variable. Variable values can be read and changed.

In [19]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 9.], dtype=float32)>

## Create a variable. Only the initial value needs to be provided.
var_1 = tf.Variable(4*tf.ones(2,3))
var_1

In [23]:
# Read the variable value.
print("Value of the variable var_1:", var_1.read_value())
# Assign a variable value.
var_value_1 = [[1, 2, 3], [4, 5, 6]]
var_1.assign(var_value_1)
print("Value of the variable var_1 after the assignment:", var_1.read_value())

Value of the variable var_1: tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(5, 3), dtype=float32)


ValueError: Shapes (5, 3) and (2, 3) are incompatible

In [14]:
# Variable addition
var_1.assign_add(tf.ones([2, 3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>


### 1.2.1.2  Tensor Slicing and Indexing
#### 1.2.1.2.1  Slicing
- Tensor slicing methods include:
  - [start: end]: extracts a data slice from the start position to the end position of the tensor.
  - [start:end:step] or [::step]: extracts a data slice at an interval of step from the start position to the end position of the tensor.
  - [::-1]: slices data from the last element.
  - '...': indicates a data slice of any length.

## Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tensor_h = tf.random.normal([2,3,4])
tensor_h

In [39]:
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 0.3264129 ,  0.27895576, -0.9666431 ],
         [-0.28996465,  0.7546892 ,  1.9307919 ],
         [-0.34496933, -1.2426192 ,  1.2129008 ],
         ...,
         [-0.6952881 , -1.4162931 , -0.43920645],
         [-1.0463091 , -1.5944855 ,  0.29268524],
         [ 1.7662923 ,  0.34818107, -0.19025818]],

        [[ 0.52402717,  0.01378755, -0.08374947],
         [ 0.5785747 ,  0.6589598 ,  0.07612512],
         [-0.8770482 , -2.352875  , -0.22594248],
         ...,
         [-0.714165  , -0.12942502,  0.06598176],
         [-1.0150676 ,  0.5746088 , -1.6364552 ],
         [ 0.73780537,  0.01828147,  1.1737319 ]],

        [[ 0.4823744 , -0.4834205 , -0.5923167 ],
         [ 0.5422618 ,  1.1718302 ,  0.8359285 ],
         [-1.1451828 ,  2.7692719 , -0.40657797],
         ...,
         [ 0.25345445,  1.0488224 ,  0.7047369 ],
         [ 2.097427  ,  0.9483373 , -0.85790074],
         [-1.3152928 , -0.06999412,  0.1243494

In [35]:
# Extract the first image.
tensor_h[:, :, 2]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.6384951 ,  0.6191002 , -1.371334  ],
       [ 0.48717734, -0.29717663, -0.26878172]], dtype=float32)>

In [37]:
# Extract one slice at an interval of two images.
tensor_h[::1, ...]

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[-0.1815408 ,  1.6070951 ,  1.7767813 ,  0.07453974],
        [-0.5905525 , -0.65095484, -0.17399302,  0.7154641 ],
        [ 0.305217  , -1.4403421 , -1.0302207 , -0.33325818]],

       [[-0.9295179 ,  0.21188092, -0.4256927 ,  0.88601035],
        [ 0.02976389,  0.9278227 , -0.19514447, -1.0209032 ],
        [ 0.9398715 ,  0.3682283 , -0.25325668, -0.38929498]],

       [[-1.3547077 , -0.78513145, -0.61368626,  0.89923984],
        [ 0.42976606, -0.71911347, -0.0470489 ,  0.3842623 ],
        [-0.7699318 , -1.0182682 ,  2.416296  ,  0.6309644 ]]],
      dtype=float32)>

In [38]:
# Slice data from the last element.
tensor_h[::-1]

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[-1.3547077 , -0.78513145, -0.61368626,  0.89923984],
        [ 0.42976606, -0.71911347, -0.0470489 ,  0.3842623 ],
        [-0.7699318 , -1.0182682 ,  2.416296  ,  0.6309644 ]],

       [[-0.9295179 ,  0.21188092, -0.4256927 ,  0.88601035],
        [ 0.02976389,  0.9278227 , -0.19514447, -1.0209032 ],
        [ 0.9398715 ,  0.3682283 , -0.25325668, -0.38929498]],

       [[-0.1815408 ,  1.6070951 ,  1.7767813 ,  0.07453974],
        [-0.5905525 , -0.65095484, -0.17399302,  0.7154641 ],
        [ 0.305217  , -1.4403421 , -1.0302207 , -0.33325818]]],
      dtype=float32)>


#### 1.2.1.2.2  Indexing
The basic format of an index is a[d1][d2][d3].

In [40]:
# Obtain the pixel in the position [20,40] in the second channel of the first image.
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.3538269>

- If the indexes of data to be extracted are nonconsecutive, tf.gather and tf.gather_nd are commonly used for data extraction in TensorFlow.
- To extract data from a particular dimension: 
  - tf.gather(params, indices,axis=None):
    - params: input tensor
    - indices: index of the data to be extracted
    - axis: dimension of the data to be extracted

In [42]:
# Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).
indices = [0, 3]
tf.gather(tensor_h, axis=0, indices=indices, batch_dims=1)

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[ 0.3264129 ,  0.27895576, -0.9666431 ],
         [-0.28996465,  0.7546892 ,  1.9307919 ],
         [-0.34496933, -1.2426192 ,  1.2129008 ],
         ...,
         [-0.6952881 , -1.4162931 , -0.43920645],
         [-1.0463091 , -1.5944855 ,  0.29268524],
         [ 1.7662923 ,  0.34818107, -0.19025818]],

        [[ 0.52402717,  0.01378755, -0.08374947],
         [ 0.5785747 ,  0.6589598 ,  0.07612512],
         [-0.8770482 , -2.352875  , -0.22594248],
         ...,
         [-0.714165  , -0.12942502,  0.06598176],
         [-1.0150676 ,  0.5746088 , -1.6364552 ],
         [ 0.73780537,  0.01828147,  1.1737319 ]],

        [[ 0.4823744 , -0.4834205 , -0.5923167 ],
         [ 0.5422618 ,  1.1718302 ,  0.8359285 ],
         [-1.1451828 ,  2.7692719 , -0.40657797],
         ...,
         [ 0.25345445,  1.0488224 ,  0.7047369 ],
         [ 2.097427  ,  0.9483373 , -0.85790074],
         [-1.3152928 , -0.06999412,  0.1243494

tf.gather_nd allows data extraction from multiple dimensions:
- tf.gather_nd(params,indices):
  - params: input tensor
  - indices: indexes of the data to be extracted, which is generally a multidimensional list.

In [22]:
# Extract the pixel in [1,1] from the first dimension of the first image and the pixel in [2,2] from the first dimension of the second image in tensot_h ([4,100,100,3]).
indices = [[0, 1, 1, 0], [1, 2, 2, 0]]
# Understand that we have (samples, image) where image is (100, 100, 3)
# So with [0, 1, 1, 0] we get (0, (1, 1, 0)) or tensor_h[0, 1, 1, 0]
# And with [1, 2, 2, 0] we get (1, (2, 2, 0)) or tensor_h[1, 2, 2, 0]
tf.gather_nd(tensor_h, indices=indices)  # With this method we get them at once

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.3956844 ,  0.38977048], dtype=float32)>


### 1.2.1.3  Tensor Dimension Modification
#### 1.2.1.3.1  Dimension Display

In [43]:
const_d_1 = tf.constant([[1, 2, 3, 4,5,6]], shape=[2, 3], dtype=tf.float32)
# Three common methods for displaying a dimension:
print(const_d_1.shape)
print(const_d_1.get_shape())
print(
    tf.shape(const_d_1)
)  # The output is a tensor. The value of the tensor indicates the size of the tensor dimension to be displayed.

(2, 3)
(2, 3)
tf.Tensor([2 3], shape=(2,), dtype=int32)


As described above, .shape and .get_shape() return TensorShape objects, and tf.shape(x) returns Tensor objects.

#### 1.2.1.3.2  Dimension Reshaping
- tf.reshape(tensor,shape,name=None):
  - tensor: input tensor
  - shape: dimension of the reshaped tensor

In [44]:
reshape_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(reshape_1)
tf.reshape(reshape_1, (3, 2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>


#### 1.2.1.3.3  Dimension Expansion
- tf.expand_dims(input,axis,name=None):
  - input: input tensor
  - axis: adds a dimension after the axis dimension. When the number of dimensions of the input data is D, the axis must fall in the range of [–(D + 1), D] (included). A negative value indicates adding a dimension in reverse order.


#### 1.2.1.3.4  Dimension Squeezing
- tf.squeeze(input,axis=None,name=None):
  - input: input tensor
  - axis: If axis is set to 1, dimension 1 needs to be deleted.

In [45]:
# Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100, 100, 3], seed=1)
print("size of the original data:", expand_sample_1.shape)
print(
    "add a dimension before the first dimension (axis = 0): ",
    tf.expand_dims(expand_sample_1, axis=0).shape,
)
print(
    "add a dimension before the second dimension (axis = 1): ",
    tf.expand_dims(expand_sample_1, axis=1).shape,
)
print(
    "add a dimension after the last dimension (axis = –1): ",
    tf.expand_dims(expand_sample_1, axis=-1).shape,
)

size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)
add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)



#### 1.2.1.3.5  Transpose
- tf.transpose(a,perm=None,conjugate=False,name='transpose'):
  - a: input tensor
  - perm: tensor size sequence, generally used to transpose high-dimensional arrays
  - conjugate: indicates complex number transpose.
  - name: tensor name

In [31]:
# Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1, 100, 100, 3])
print("size of the original data:", squeeze_sample_1.shape)
squeezed_sample_1 = tf.squeeze(expand_sample_1)
print("data size after dimension squeezing:", squeezed_sample_1.shape)

size of the original data: (1, 100, 100, 3)
data size after dimension squeezing: (100, 100, 3)


In [32]:
# Input the tensor to be transposed, and call tf.transpose.
trans_sample_1 = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print("size of the original data:", trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:", transposed_sample_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


In [33]:
# perm is required for high-dimensional data transpose, and indicates the dimension sequence of the input tensor.
# The original dimension sequence of a three-dimensional tensor is [0, 1, 2] (perm), indicating the length, width, and height of high-dimensional data, respectively.
# Data dimensions can be transposed by changing the sequence of values in perm.
# Generate an $ x 100 x 200 x 3 tensor to represent four 100 x 200 three-channel color images.
trans_sample_2 = tf.random.normal([4, 100, 200, 3])
print("size of the original data:", trans_sample_2.shape)
# Exchange the length and width for the four images: The original perm value is [0,1,2,3], and the new perm value is [0,2,1,3].
transposed_sample_2 = tf.transpose(trans_sample_2, [0, 2, 1, 3])
print("size of transposed data:", transposed_sample_2.shape)

size of the original data: (4, 100, 200, 3)
size of transposed data: (4, 200, 100, 3)



#### 1.2.1.3.6  Broadcast (broadcast_to)
- broadcast_to is used to broadcast data from a low dimension to a high dimension.
  - tf.broadcast_to(input,shape,name=None):
    - input: input tensor
    - shape: size of the output tensor

In [34]:
broadcast_sample_1 = tf.constant([1, 2, 3, 4, 5, 6])
print("original data:", broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1, shape=[4, 6])
print("broadcasted data:", broadcasted_sample_1.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [35]:
# During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = tf.constant([1, 2, 3])
print(a + b)

#### 1.2.1.4  Arithmetic Operations on Tensors
##### 1.2.1.4.1  Arithmetic Operators
# Main arithmetic operations include addition (tf.add), subtraction (tf.subtract), multiplication (tf.multiply), division (tf.divide), logarithm (tf.math.log), and powers (tf.pow).
# The following describes only one addition example.

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [36]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)



#### 1.2.1.4.2  Matrix Multiplication
Matrix multiplication is implemented by calling tf.matmul.

In [37]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>


#### 1.2.1.4.3  Tensor Statistics Collection
- Methods for collecting tensor statistics include:
  - tf.reduce_min/max/mean(): calculates the minimum, maximum, and mean values.
  - tf.argmax()/tf.argmin(): calculates the positions of the maximum and minimum values.
  - tf.equal(): checks whether two tensors are equal by element.
  - tf.unique(): removes duplicate elements from tensors.
  - tf.nn.in_top_k(prediction, target, K): calculates whether the predicted value is equal to the actual value, and returns a Boolean tensor.
- The following describes how to use tf.argmax():
  - Return the position of the maximum value.
    - tf.argmax(input,axis):
      - input: input tensor
      - axis: maximum output value in the axis dimension

In [38]:
argmax_sample_1 = tf.constant([[1, 3, 2], [2, 5, 8], [7, 5, 9]])
print("input tensor:", argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column:", max_sample_1.numpy())
print("locate the maximum value by row:", max_sample_2.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
locate the maximum value by column: [2 1 2]
locate the maximum value by row: [1 2 2]



### 1.2.1.5  Dimension-based Arithmetic Operations
- In TensorFlow, a series of operations of tf.reduce_* reduce tensor dimensions. The series of operations can be performed on dimensional elements of a tensor, for example, calculating the mean value by row and calculating a product of all elements in the tensor.
- Common operations include tf.reduce_sum (addition), tf.reduce_prod (multiplication), tf.reduce_min (minimum), tf.reduce_max (maximum), tf.reduce_mean (mean value), tf.reduce_all (logical AND), tf.reduce_any (logical OR), and tf.reduce_logsumexp (log(sum(exp))).
- The methods for using these operations are similar. The following describes how to use tf.reduce_sum.
- Calculate the sum of elements in all dimensions of a tensor.
  - tf.reduce_sum(input_tensor, axis=None, keepdims=False,name=None):
    - input_tensor: input tensor
    - axis: axis to be calculated. If this parameter is not specified, the mean value of all elements is calculated.
    - keepdims: indicates whether to keep dimensions. If this parameter is set to True, the output result retains the shape of the input tensor. If this parameter is set to False, dimensions of the output result decrease.
    - name: operation name

In [39]:
reduce_sample_1 = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print("original data", reduce_sample_1.numpy())
print(
    "calculate the sum of all elements in the tensor (axis = None): ",
    tf.reduce_sum(reduce_sample_1, axis=None).numpy(),
)
print(
    "calculate the sum of elements in each column by column (axis = 0): ",
    tf.reduce_sum(reduce_sample_1, axis=0).numpy(),
)
print(
    "calculate the sum of elements in each column by row (axis = 1): ",
    tf.reduce_sum(reduce_sample_1, axis=1).numpy(),
)

original data [[1 2 3]
 [4 5 6]]
calculate the sum of all elements in the tensor (axis = None):  21
calculate the sum of elements in each column by column (axis = 0):  [5 7 9]
calculate the sum of elements in each column by row (axis = 1):  [ 6 15]



### 1.2.1.6  Tensor Concatenation and Splitting
#### 1.2.1.6.1  Tensor Concatenation
- In TensorFlow, tensor concatenation operations include:
  - tf.contact(): concatenates vectors based on the specified dimension, while keeping other dimensions unchanged.
  - tf.stack(): changes a group of R dimensional tensors to R+1 dimensional tensors, with the dimensions changed after the concatenation.
tf-ncat(values, axis, name='concat'):
  - values: input tensor
  - axis: dimension to concatenate
  - name: operation name

In [40]:
concat_sample_1 = tf.random.normal([4, 100, 100, 3])
concat_sample_2 = tf.random.normal([40, 100, 100, 3])
print("sizes of the original data:", concat_sample_1.shape, concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1, concat_sample_2], axis=0)
print("size of the concatenated data:", concated_sample_1.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)
size of the concatenated data: (44, 100, 100, 3)


A dimension can be added to an original matrix in the same way. axis determines the position of the dimension.
  - tf.stack(values, axis=0, name='stack'):
    - values: input tensors, a group of tensors with the same shape and data type
    - axis: dimension to concatenate
    - name: operation name

In [42]:
stack_sample_1 = tf.random.normal([100, 100, 3])
stack_sample_2 = tf.random.normal([100, 100, 3])
print("sizes of the original data: ", stack_sample_1.shape, stack_sample_2.shape)
# Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2], axis=0)
print("size of the concatenated data:", stacked_sample_1.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)



#### 1.2.1.6.2  Tensor Splitting
- In TensorFlow, tensor splitting operations include:
  - tf.unstack(): splits a tensor by a specific dimension.
  - tf.split(): splits a tensor into a specified number of sub tensors based on a specific dimension.
- tf.split() is more flexible than tf.unstack().
- tf.unstack(value,num=None,axis=0,name='unstack'):
  - value: input tensor
  - num: indicates that a list containing num elements is output. The value of num must be the same as the number of elements in the specified dimension. This parameter can generally be ignored.
  - axis: specifies the dimension based on which the tensor is split.
  - name: operation name

In [43]:
# Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1, axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-1.0016253 ,  0.26051822,  1.7687274 ],
         [-0.50249374, -0.3258857 , -2.0099938 ],
         [-0.7239237 ,  0.70923704, -1.1537834 ],
         ...,
         [-2.192112  , -0.46967924, -0.14267786],
         [ 0.4953367 , -0.5268708 ,  2.0384674 ],
         [-1.0021414 ,  1.3635811 , -0.82752   ]],
 
        [[ 0.27292117,  0.4977804 , -0.27335963],
         [-1.8584898 , -0.99906325,  0.7514743 ],
         [ 1.7238576 , -0.37615556,  0.7526632 ],
         ...,
         [ 0.29846996,  1.3420974 , -0.62700534],
         [-0.537686  , -0.05188088, -2.4036608 ],
         [-0.52722794,  1.2681376 , -0.35410273]],
 
        [[ 1.0604855 ,  0.69024026,  1.1821338 ],
         [ 0.8687667 ,  0.13040993, -0.68880635],
         [ 0.6510132 , -0.9828226 , -0.24002507],
         ...,
         [-0.81382203,  0.23761371,  0.01619843],
         [ 0.56032425,  0.78772515, -0.4091408 ],
         [ 0.85448205, -0.5573653 ,  0.4801265


- tf.split(value, num_or_size_splits, axis=0):
  - value: input tensor
  - num_or_size_splits: number of sub tensors
  - axis: specifies the dimension based on which the tensor is split.
tf-lit() splits a tensor in either of the following ways:
  - If the value of num_or_size_splits is an integer, the tensor is evenly split into sub tensors in the specified dimension (axis = D).
  - If the value of num_or_size_splits is a vector, the tensor is split into sub tensors based on the element value of the vector in the specified dimension (axis = D).

In [47]:
import numpy as np

split_sample_1 = tf.random.normal([10, 100, 100, 3])
print("size of the original data:", split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5, axis=0)
print(
    "size of the split data when m_or_size_splits is set to 10: ",
    np.shape(splited_sample_1),
)
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3, 5, 2], axis=0)
print(
    "sizes of the split data when num_or_size_splits is set to [3,5,2]:",
    np.shape(splited_sample_2[0]),
    np.shape(splited_sample_2[1]),
    np.shape(splited_sample_2[2]),
)
splited_sample_3 = tf.split(split_sample_1, num_or_size_splits=[8, 2], axis=0)
print(
    "sizes of the split data when num_or_size_splits is set to [8,2]:",
    np.shape(splited_sample_3[0]),
    np.shape(splited_sample_3[1]),
   
)

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [8,2]: (8, 100, 100, 3) (2, 100, 100, 3)



### 1.2.1.7  Tensor Sorting
- In TensorFlow, tensor sorting operations include:
  - tf.sort(): sorts tensors in ascending or descending order and returns the sorted tensors.
  - tf.argsort(): sorts tensors in ascending or descending order, and returns tensor indexes.
  - tf.nn.top_k(): returns the first k maximum values.
tf-rt/argsort(input, direction, axis):
  - input: input tensor
  - direction: sorting order, which can be set to DESCENDING (descending order) or ASCENDING (ascending order). The default value is ASCENDING.
  - axis: sorting by the dimension specified by axis. The default value of axis is –1, indicating the last dimension.

In [45]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:", sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:", sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1, direction="ASCENDING")
print("indexes of elements in ascending order:", sorted_sample_2.numpy())

input tensor: [8 6 9 7 5 3 0 2 4 1]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements in ascending order: [6 9 7 5 8 4 1 3 0 2]


- tf.nn.top_k(input,K,sorted=TRUE):
  - input: input tensor
  - K: the first k values to be output and their indexes
  - sorted: When sorted is set to TRUE, the tensor is sorted in ascending order. When sorted is set to FALSE, the tensor is sorted in descending order.
Re-n two tensors:
  - values: k maximum values in each row
  - indices: positions of elements in the last dimension of the input tensor

In [46]:
values, index = tf.nn.top_k(sort_sample_1, 5)
print("input tensor:", sort_sample_1.numpy())
print("first five values in ascending order:", values.numpy())
print("indexes of the first five values in ascending order:", index.numpy())

input tensor: [8 6 9 7 5 3 0 2 4 1]
first five values in ascending order: [9 8 7 6 5]
indexes of the first five values in ascending order: [2 0 3 1 4]



1.2.2  Eager Execution of TensorFlow 2.x
- The eager execution mode of TensorFlow is a type of imperative programming, which is the same as native Python. When you perform a particular operation, the system immediately returns a result.
- Graph mode:
- TensorFlow 1.0 adopts the graph mode to first build a computational graph, enable a session, and then feed actual data to obtain a result.
- In eager execution mode, code debugging is easier, but the code execution efficiency is lower.
- The following implements simple multiplication by using TensorFlow to compare the differences between the eager execution mode and the graph mode.

In [ ]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

In [51]:
# Use the syntax of TensorFlow 1.x in TensorFlow 2.x. You can install the v1 compatibility package in TensorFlow 2.0 to inherit the TensorFlow 1.x code and disable the eager execution mode.
import tensorflow.compat.v1 as tf


# Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
a
b


# Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


Restart the kernel to restore TensorFlow 2.0 and enable the eager execution mode. Another advantage of the eager execution mode lies in availability of native Python functions, for example, the following condition statement:

In [1]:
import tensorflow as tf

thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)
if thre_1.numpy() > 0.5:
    y = tf.matmul(x, x)
else:
    y = tf.add(x, x)

tf.Tensor(0.010016441, shape=(), dtype=float32)


With the eager execution mode, this dynamic control flow can generate a NumPy value extractable by a tensor, without using operators such as tf.cond and tf.while provided in graph mode.


## 1.2.3  AutoGraph of TensorFlow 2.x
When used to comment out a function, the decorator tf.function can be called like any other function. tf.function will be compiled into a graph, so that it can run more efficiently on a GPU or TPU. In this case, the function becomes an operation in TensorFlow. The function can be directly called to output a return value. However, the function is executed in graph mode and intermediate variable values cannot be directly viewed.

In [2]:
@tf.function
def simple_nn_layer(w, x, b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x) + b)


w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype="float32")

simple_nn_layer(w, x, b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.0012102, 0.8567029, 1.0545027],
       [1.2461724, 1.7495183, 1.3102707],
       [1.2327646, 1.6710498, 1.3720185]], dtype=float32)>

According to the output result, the value of b in the function cannot be viewed directly, but the return value can be viewed using .numpy().
The following compares the performance of the graph mode and eager execution mode by performing the same operation (computation of one CNN layer).

In [8]:
# Use the timeit module to measure the execution time of a small code segment.
import timeit

# Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=32, kernel_size=2, strides=(1, 1))

# Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
    return CNN_cell(image)


image = tf.zeros([100, 200, 200, 3])

# Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)
# Call timeit.timeit to measure the time required for executing the code 10 times.
print(
    "time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:",
    timeit.timeit(lambda: CNN_cell(image), number=10),
)
print(
    "time required for performing the computation of one CNN layer in graph mode:",
    timeit.timeit(lambda: CNN_fn(image), number=10),
)

time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode: 0.004066933004651219
time required for performing the computation of one CNN layer in graph mode: 0.0027632830024231225


The comparison shows that the code execution efficiency in graph mode is much higher. Therefore, the @tf.function function can be used to improve the code execution efficiency.